### ISSUE TITLE
Support for defaultProps will be removed with Typescript

### ISSUE THREAD

**Issue by lutfi-haslab** [mbpictures/react-chat-module#2]
Got error warning messages:
- app-index.js:33 Warning: Chat: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- app-index.js:33 Warning: SendMessage: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- app-index.js:33 Warning: Input: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- app-index.js:33 Warning: FileAttachment: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by mbpictures** [comment]
Thanks for reporting this issue, a new update has been published. Please update to version 1.1.2 and check if the warning persists.
